vich_uploader:
  db_driver: orm
  mappings:
    property_images:
      uri_prefix: "%app.path.property_images%"
      upload_destination: "%kernel.project_dir%/public%app.path.property_images%"
      # namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

      # inject_on_load: false
      # delete_on_update: true
      # delete_on_remove: true
